version: '3'
services:
  # Consul
  consul:
    image: consul
    ports:
      - '8500:8500'

  # patroni
  patroni:
    build: .
    image: nomad-pgsql-patroni:16.1-1.tsdb_gis
    environment:
      PGDATA: /alloc/data
    ports:
      - '5433:5432'
      - '8008:8008'
    tmpfs:
      - /alloc
    volumes:
      - './example-patroni.yml:/secrets/patroni.yml'
