on:
  push:
    branches: [ PG_15 ]
  pull_request:
    branches: [ PG_15 ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: Linux/amd64, linux/arm64/v8
          push: true
          tags: ghcr.io/sstent/nomad-pgsql-patroni:pg15,  ghcr.io/sstent/nomad-pgsql-patroni:latest
          
